/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author OWNER
 */
import java.awt.*;
import java.math.*;

public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    Graphics g;
    String State = "";
    int lx,ly;
    public Panel() {
        initComponents();
        g = Panel.getGraphics();
        Panel.paintComponents(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClear1 = new javax.swing.JButton();
        btnLine1 = new javax.swing.JButton();
        btnRectangle1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLine = new javax.swing.JButton();
        btnRectangle = new javax.swing.JButton();
        btnOval = new javax.swing.JButton();
        btnTriangle = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRed = new javax.swing.JButton();
        btnGreen = new javax.swing.JButton();
        btnBlue = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputX = new javax.swing.JTextField();
        inputY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        translasiRight = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inputderajat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonRotation = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        translasiLeft = new javax.swing.JButton();

        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        btnLine1.setText("Line");
        btnLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLine1ActionPerformed(evt);
            }
        });

        btnRectangle1.setText("Rectangle");
        btnRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangle1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnLine.setText("Line");
        btnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineActionPerformed(evt);
            }
        });

        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        btnOval.setText("Oval");
        btnOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOvalActionPerformed(evt);
            }
        });

        btnTriangle.setText("Triangle");
        btnTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangleActionPerformed(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Shape");

        jLabel2.setText("Fill Color");

        btnRed.setText("Red");
        btnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedActionPerformed(evt);
            }
        });

        btnGreen.setText("Green");
        btnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenActionPerformed(evt);
            }
        });

        btnBlue.setText("Blue");
        btnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlueActionPerformed(evt);
            }
        });

        jLabel3.setText("Translasi");

        inputX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputXActionPerformed(evt);
            }
        });

        jLabel4.setText("X : ");

        jLabel5.setText("Y : ");

        translasiRight.setText("Right");
        translasiRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translasiRightActionPerformed(evt);
            }
        });

        jLabel6.setText("Rotasi");

        jLabel7.setText("Angle :");

        buttonRotation.setText("Rotate");
        buttonRotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotationActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Grafika Final Project");

        translasiLeft.setText("Left");
        translasiLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translasiLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addGap(552, 552, 552))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRectangle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOval, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTriangle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(translasiLeft)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(translasiRight))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputY)
                                        .addComponent(inputX)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(8, 8, 8)
                                        .addComponent(inputderajat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)))
                            .addComponent(buttonRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRectangle)
                        .addGap(4, 4, 4)
                        .addComponent(btnOval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTriangle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGreen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBlue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(translasiRight)
                            .addComponent(translasiLeft))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputderajat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRotation)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Panel.repaint();
        g.setColor(Color.black);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        setPanelBlank();
        g.drawLine(230, 250, 100, 200);
        State = "Garis";
        lx = 230;
        ly = 250;
    }//GEN-LAST:event_btnLineActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        setPanelBlank();
        g.drawRect(230, 250, 200, 200);
        State = "rectangle";
        lx = 230;
        ly = 250;
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnOvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOvalActionPerformed
        setPanelBlank();
        g.drawOval(230, 250, 200, 200);
        State = "Oval";
        lx = 230;
        ly = 250;
    }//GEN-LAST:event_btnOvalActionPerformed

    private void btnTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangleActionPerformed
        setPanelBlank();
        State = "Triangle";
        int x[] = {50,150,250};
        int y[] = {250,50,250};
        g.drawPolygon(x,y,x.length);
    }//GEN-LAST:event_btnTriangleActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLine1ActionPerformed

    private void btnRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRectangle1ActionPerformed

    private void btnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedActionPerformed
        setPanelBlank();
        if(State == "rectangle"){
            g.setColor(Color.red);
            g.fillRect(lx, ly, 200, 200);
        }else if(State == "Oval"){
            g.setColor(Color.red);
            g.fillOval(lx, ly, 200, 200);
        }else if(State == "Triangle"){
            g.setColor(Color.red);
            int x[] = {50,200,250};
            int y[] = {250,50,250};
            g.fillPolygon(x,y,x.length);
        }
    }//GEN-LAST:event_btnRedActionPerformed

    private void btnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenActionPerformed
        setPanelBlank();
        if(State == "rectangle"){
            g.setColor(Color.green);
            g.fillRect(lx, ly, 200, 200);
        }else if(State == "Oval"){
            g.setColor(Color.green);
            g.fillOval(lx, ly, 200, 200);
        }else if(State == "Triangle"){
            g.setColor(Color.green);
            int x[] = {50,200,250};
            int y[] = {250,50,250};
            g.fillPolygon(x,y,x.length);
        }
    }//GEN-LAST:event_btnGreenActionPerformed

    private void btnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueActionPerformed
        setPanelBlank();
        if(State == "rectangle"){
            g.setColor(Color.blue);
            g.fillRect(lx, ly, 200, 200);
        }else if(State == "Oval"){
            g.setColor(Color.blue);
            g.fillOval(lx, ly, 200, 200);
        }else if(State == "Triangle"){
            g.setColor(Color.blue);
            int x[] = {50,200,250};
            int y[] = {250,50,250};
            g.fillPolygon(x,y,x.length);
        }
    }//GEN-LAST:event_btnBlueActionPerformed

    private void inputXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputXActionPerformed

    private void translasiRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translasiRightActionPerformed
        setPanelBlank();
        
        int tx,ty;
        tx = Integer.parseInt(getx());
        ty = Integer.parseInt(gety());
        if(State == "rectangle"){
            g.drawRect(lx + tx, ly + ty, 200, 200);
            lx += tx;
            ly +=ty;
        }else if(State == "Oval"){
            g.drawOval(lx + tx, ly + ty, 200, 200);
            lx += tx;
            ly +=ty;
        }else if(State == "Triangle"){
            int x[] = {50 + tx,200 + tx,250 + tx};
            int y[] = {250 + ty,50 + ty,250 + ty};
            g.drawPolygon(x,y,x.length);
            lx -= tx;
            ly -=ty;
        }else if(State == "Garis"){
            g.drawLine(lx + tx, ly + ty, 100, 200);
            lx -= tx;
            ly -=ty;
        }
    }//GEN-LAST:event_translasiRightActionPerformed

    private void buttonRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotationActionPerformed
        int angle = Integer.parseInt(getderajat());
        double move = (angle * Math.PI / 180);
        Graphics2D graphics2D = (Graphics2D)g.create();
        setPanelBlank();
        
        if(State == "rectangle"){
            graphics2D.translate(lx, ly);
            graphics2D.rotate(move);
            graphics2D.drawRect(0, 0, 200, 200);
        }else if(State == "Triangle"){
//            int x[] = {50 + tx,200 + tx,250 + tx};
//            int y[] = {250 + ty,50 + ty,250 + ty};
//            g.drawPolygon(x,y,x.length);
        }else if(State == "Garis"){
            graphics2D.translate(lx, ly);
            graphics2D.rotate(move);
            graphics2D.drawLine(0, 0, 100, 200);
        }
    }//GEN-LAST:event_buttonRotationActionPerformed

    private void translasiLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translasiLeftActionPerformed
        setPanelBlank();
        
        int tx,ty;
        tx = Integer.parseInt(getx());
        ty = Integer.parseInt(gety());
        if(State == "rectangle"){
            g.drawRect(lx - tx, ly - ty, 200, 200);
            lx -= tx;
            ly -=ty;
        }else if(State == "Oval"){
            g.drawOval(lx - tx, ly - ty, 200, 200);
            lx -= tx;
            ly -=ty;
        }else if(State == "Triangle"){
            int x[] = {50 - tx,200 - tx,250 - tx};
            int y[] = {250 - ty,50 - ty,250 - ty};
            g.drawPolygon(x,y,x.length);
            lx -= tx;
            ly -=ty;
        }else if(State == "Garis"){
            g.drawLine(lx - tx, ly - ty, 100, 200);
            lx -= tx;
            ly -=ty;
        }
    }//GEN-LAST:event_translasiLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnBlue;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnLine;
    private javax.swing.JButton btnLine1;
    private javax.swing.JButton btnOval;
    private javax.swing.JButton btnRectangle;
    private javax.swing.JButton btnRectangle1;
    private javax.swing.JButton btnRed;
    private javax.swing.JButton btnTriangle;
    private javax.swing.JButton buttonRotation;
    private javax.swing.JTextField inputX;
    private javax.swing.JTextField inputY;
    private javax.swing.JTextField inputderajat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton translasiLeft;
    private javax.swing.JButton translasiRight;
    // End of variables declaration//GEN-END:variables

    public String getx(){
        return inputX.getText();
    }
    
    public String gety(){
        return inputY.getText();
    }
    
    public String getderajat(){
        return inputderajat.getText();
    }
    
    void setPanelBlank(){
        g.setColor(Color.WHITE); // Set the color to white
        g.fillRect(0, 0, Panel.getWidth(), Panel.getHeight()); // Clear the canvas
        g.setColor(Color.BLACK);
    }
    
}
